### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by RBirmiwal** [XpressAI/xircuits#285]
Hello, I am trying to install and run a tutorial as provided by your documentation. This line causes an error: xircuits install pytorch

```bash
Traceback (most recent call last):
  File "/Users/birm560/opt/anaconda3/envs/neuromancer2/bin/xircuits", line 8, in <module>
    sys.exit(main())
  File "/Users/birm560/opt/anaconda3/envs/neuromancer2/lib/python3.10/site-packages/xircuits/start_xircuits.py", line 215, in main
    args.func(args, unknown_args)
  File "/Users/birm560/opt/anaconda3/envs/neuromancer2/lib/python3.10/site-packages/xircuits/start_xircuits.py", line 93, in cmd_install_library
    request_submodule_library(component_library_path)
  File "/Users/birm560/opt/anaconda3/envs/neuromancer2/lib/python3.10/site-packages/xircuits/handlers/request_submodule.py", line 35, in request_submodule_library
    submodule_path, submodule_url = get_submodule_config(component_library_query)
TypeError: cannot unpack non-iterable NoneType object
```

I am a software developer for a scientific machine learning library (https://github.com/pnnl/neuromancer) and am interested in using xircuits to develop a visual programming alternative for our users.

**Comment by MFA-X-AI** [comment]
Thanks for raising it up! The cause of it was a small typo where the newest 5 submodules were ported in `xai_component` instead of `xai_components`. We've released the bugfix in the recent 1.9.4. https://github.com/XpressAI/xircuits/releases/tag/v1.9.4

To apply the updates, simply reinstall xircuits, as well as remove the .xircuits from your working directory. 

> https://github.com/pnnl/neuromancer
Very cool. Looking forward to see it run on Xircuits. Let us know if you run into anything else.

**Comment by wmeddie** [comment]
That is very cool.  Feel free to reach out to me or talk about Xircuits on our discord https://discord.com/invite/vgEg2ZtxCw

**Comment by wmeddie** [comment]
Definitely some things on our todo list that will be required to integrate something like neuromancer (like making a math expression node), but hopefully we can work together on that.
